### ISSUE TITLE
Message encryption.

### ISSUE THREAD

**Issue by crocchietta** [metio/matrix-alertmanager-receiver#64]
Hello.
I'm trying out the app. I do receive messages in the living room but they are not encrypted.

Is the encryption well taken into account by the application?

**Comment by sebhoss** [comment]
hey,

thanks for opening this! Message encryption is currently not supported, but it's something I would love to have in the code base. I'll keep this open to track that feature.

**Comment by crocchietta** [comment]
Unless I'm mistaken, it's the mautrix-go library that is used. Unless I'm mistaken, it's the mautrix-go library that is used. And it seems to offer this possibility. (https://github.com/mautrix/go/issues/3).

It would also be nice if the application could directly manage the use of a proxy to reach the matrix server.
Maybe by adding a proxy: option to the matrix part of the configuration file :

```
# configuration for the Matrix connection
matrix:
  homeserver-url: https://xxxxxxxx                                        # FQDN of the homeserver
  user-id: "@xxxxxxxxxxxxxxxxxxxx:yyyyyyyyyyyyyyyyy"   # ID of the user used by this service
  access-token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             # Access token for the user ID
  # define short names for Matrix room ID
  room-mapping:
   simple-name "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  proxy: http://proxy.x.y:3128
```
